[env:rpipico2w]
platform  = https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
board     = rpipico2w
framework = arduino

lib_deps =
    Bodmer/TFT_eSPI @ ^2.5.43
    lvgl/lvgl @ ^8.3.11
    adafruit/Adafruit seesaw Library @ ^1.7.5
    adafruit/Adafruit BusIO @ ^1.14.5
    bitbank2/JPEGDEC @ ^1.2.7

build_flags =
    ; TFT_eSPI ILI9341 config
    -DUSER_SETUP_LOADED
    -DILI9341_DRIVER
    -DTFT_MOSI=19
    -DTFT_SCLK=18
    -DTFT_MISO=16
    -DTFT_CS=17
    -DTFT_DC=20
    -DTFT_RST=21
    -DTFT_BL=-1
    -DSPI_FREQUENCY=40000000
    -DSPI_READ_FREQUENCY=20000000
    ; LVGL
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_COLOR_DEPTH=16
    ; TinyUSB for USB Mass Storage
    -DUSE_TINYUSB

board_build.core   = earlephilhower
board_build.f_cpu  = 150000000L

monitor_speed = 115200
