#!/usr/bin/env python3
"""Generate a KiCad 7+ hierarchical schematic skeleton for the ProtoHUD carrier.

Emits ProtoHUD-Carrier.kicad_pro, a root sheet with one hierarchical sheet per
functional block, and an annotated stub sub-sheet for each block (parts list +
the exact BCM net names from PINMAP.md as on-canvas text). Re-run to regenerate.

This is a SKELETON: it opens in KiCad as the hierarchy; you place symbols and
draw nets per the annotations. Targets the KiCad 7 file format (v8 upgrades it
on first save).
"""
import os, uuid

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = "ProtoHUD-Carrier"
VERSION = "20230121"           # KiCad 7 schematic format
GEN = "protohud_skeleton"

def u():                       # fresh UUID string
    return str(uuid.uuid4())

# ── Sheet plan: (file, title, content lines) ────────────────────────────────
# Two-brain carrier: CM5 drives only HUB75; RP2354B owns all other I/O.
# See ../RP2354-IO.md, ../PINMAP.md, ../BLOCK-DIAGRAM.md.
SHEETS = [
    ("power", "1. Power", [
        "POWER — 5 V input from backpack umbilical (external 40V->5V buck off-board)",
        "Parts: J1 5V in (XT60) + remote-sense pair, bulk cap >=2200uF,",
        "  5V reverse-polarity P-FET, TVS SMBJ5.0A, per-rail bulk caps + fuses,",
        "  +3V3_RP LDO/buck (>=500mA), optional INA219 x N telemetry.",
        "Rails: +5V (CM5+USB), +5V_PANEL (fused), +5V_LED (fused),",
        "  +V_SERVO 5-6V (fused), +3V3_RP (local LDO), GND (common star).",
        "See POWER.md.",
    ]),
    ("cm5", "2. CM5 (HUB75 + cameras + USB)", [
        "CM5 — compute module; drives ONLY HUB75 (+ CSI / HDMI / USB host)",
        "Parts: 2x Hirose DF40C-100DS-0.4V(51), decoupling per CM5 guide,",
        "  nRPIBOOT jumper + USB (eMMC flash), spare-GPIO debug header.",
        "Nets: HUB75 BCM 4-27 (see PINMAP.md) -> face_buffer; +5V, +3V3, GND.",
        "Non-HUB75 CM5 lines: BCM7=RP_RUN, BCM8=RP_BOOTSEL (RP2354B control),",
        "  BCM18/BCM19 = fan zone 1/2 (low-side MOSFET gates, sys::FanController).",
        "All other peripheral I/O lives on the RP2354B, not here.",
    ]),
    ("face_buffer", "3. Face Buffer (HUB75)", [
        "POPULATED separately by populate_face_buffer.py — HUB75-only, CM5 side.",
        "U1/U2 74AHCT245 @5V -> J2 (2x8 IDC). Not regenerated by this script.",
    ]),
    ("rp2354_io", "4. RP2354B I/O MCU", [
        "RP2354B I/O COPROCESSOR — core (USB-CDC to CM5 via hub)",
        "Parts: RP2354B (QFN-80, 48 GPIO, 2MB flash), 12 MHz xtal + load caps,",
        "  decoupling/core-reg per RP2350 guide, BOOTSEL + RUN buttons, SWD hdr,",
        "  SW1 USB selector (hub<->J12), J12 USB-C program port, USBLC6 ESD.",
        "Nets: RP_DP/DM -> SW1; +3V3_RP, +5V, GND.  DBG_TX=GP0 DBG_RX=GP1.",
        "See RP2354-IO.md for the full GP allocation.",
    ]),
    ("rp2354_face", "5. MAX7219 Buffer (RP2354B)", [
        "MAX7219 face backend — RP2354B side, 3.3V->5V",
        "Parts: U10 74AHCT245 @5V, J3 MAX7219 header (5V/GND/DIN/CLK/CS x4), decoupl.",
        "Nets: MX_CLK=GP2 MX_DIN=GP3 MX_CS1..4=GP7..GP10 (SPI0), buffered to 5V.",
        "Runs alongside HUB75 (different brain). See MULTI-BACKEND.md.",
    ]),
    ("leds", "6. WS2812 LEDs (RP2354B)", [
        "WS2812 ACCESSORY LEDS — RP2354B side, 4 zones",
        "Parts: U11 74AHCT125 quad @5V, J4 LED conns x4 (5V/DIN/GND), bulk caps, R.",
        "Nets: LED1..4_DAT = GP16..GP19 (PIO), buffered to 5V; +5V_LED (fused).",
    ]),
    ("sensors_i2c", "7. Sensors I2C (RP2354B)", [
        "I2C0 sensors — RP2354B master (3V3, direct)",
        "Parts: 4.7k SDA0/SCL0 pull-ups to +3V3_RP, J5 I2C/Qwiic + INT pin,",
        "  optional MCP23017/ADS1115/PCA9685, STEMMA QT expansion.",
        "Nets: SDA0=GP4, SCL0=GP5, SENS_INT=GP6, +3V3_RP, GND.",
        "Addrs: BNO055 0x28, MPU9250 0x68, MPR121 0x5A, BH1750 0x23.",
        "See IO-EXPANSION.md.",
    ]),
    ("servos", "8. Servos (RP2354B)", [
        "SERVOS — 8 channels, RP2354B PWM (3.3V signal direct)",
        "Parts: J20-J27 eight 3-pin headers (SIG / +V_SERVO / GND),",
        "  +V_SERVO rail fuse + bulk cap >=1000uF, optional 6V buck.",
        "Nets: SRV1..8 = GP20..GP27.  +V_SERVO 5-6V, GND.",
        "Optional 74AHCT buffer footprint if 5V servo signal is needed.",
    ]),
    ("gpio_buttons", "9. Buttons / Boop (RP2354B)", [
        "BUTTONS / BOOP — RP2354B GPIO (MCU debounce)",
        "Parts: J6 header, series R, optional ESD array.",
        "Nets: BTN1..10 = GP28..GP37, +3V3_RP, GND.",
        "Wire switches to GND (active_low); internal pull-ups in firmware.",
    ]),
    ("usb", "10. USB Hub", [
        "USB — in-helmet hub + RP2354B uplink + backpack uplink",
        "Parts: USB2514B/2517 hub, J9 downstream (RP2354B via SW1 / RP2350 audio /",
        "  knob / LoRa / VITURE / cams), J11 backpack USB uplink (phone->CM5),",
        "  USBLC6 ESD on data pairs.",
        "Nets: CM5 USB D+/D-, VBUS.  RP2354B is a hub downstream device (SW1 pos A).",
    ]),
    ("cameras_display", "11. Cameras + Display (CM5)", [
        "CSI CAMERAS + HDMI — CM5 side",
        "Parts: J7/J8 22-pin 0.5mm CSI FFC (2 eyes), J10 2x HDMI + ESD array.",
        "Nets: MIPI data/clock differential pairs + cam I2C (verify against CM5",
        "  datasheet); HDMI TMDS pairs + DDC + HPD + CEC.  Length-match pairs.",
    ]),
]

# Sheets whose sub-sheet .kicad_sch is authored elsewhere — included in the
# hierarchy/project but NOT overwritten by this skeleton generator.
POPULATED = {"face_buffer"}

# Stable UUIDs (idempotent re-runs; keeps the populated face_buffer linkage at
# its hard-coded SHEET_OBJ_UUID in populate_face_buffer.py).
root_uuid = "fb9b62d2-d9b7-4b5e-86af-44187a7f9335"
sheet_uuids = {
    "power":           "7fcf71da-42d5-4843-bf7d-f52f6f1fa308",
    "cm5":             "3812e784-9e95-4c5b-856a-ca4e97dc1851",
    "face_buffer":     "eff6a452-77ae-416d-87a8-cfe219f371e8",
    "rp2354_io":       "a1b2c3d4-0001-4aaa-9bbb-000000000004",
    "rp2354_face":     "a1b2c3d4-0002-4aaa-9bbb-000000000005",
    "leds":            "833500fc-08ba-4260-bcba-d50b8d06254c",
    "sensors_i2c":     "aa17a73e-e56b-4b1f-a092-064b3bde23cb",
    "servos":          "a1b2c3d4-0003-4aaa-9bbb-000000000008",
    "gpio_buttons":    "4d61ad14-7947-4b5f-b9ac-ea72b52475d0",
    "usb":             "b12d177a-080c-49c4-8372-6cdd7e6e9f72",
    "cameras_display": "c814e905-b80c-42d1-beeb-925e48192849",
}

def effects(size=1.27, justify="left bottom", hide=False):
    h = " (hide yes)" if hide else ""
    return f"(effects (font (size {size} {size})){' (justify ' + justify + ')' if justify else ''}{h})"

def write(path, text):
    with open(os.path.join(HERE, path), "w") as fh:
        fh.write(text)

# ── Sub-sheets ──────────────────────────────────────────────────────────────
for fname, title, lines in SHEETS:
    if fname in POPULATED:
        continue                      # authored by populate_*.py — don't clobber
    texts = []
    y = 25.4
    for ln in [title, "-" * 60] + lines:
        safe = ln.replace('"', "'")
        texts.append(
            f'  (text "{safe}" (at 25.4 {y:.2f} 0) '
            f'(effects (font (size 1.5 1.5)) (justify left bottom)) (uuid {u()}))'
        )
        y += 3.0
    body = "\n".join(texts)
    write(f"{fname}.kicad_sch", f"""(kicad_sch
  (version {VERSION})
  (generator {GEN})
  (uuid {sheet_uuids[fname]})
  (paper "A3")
  (title_block
    (title "ProtoHUD Carrier — {title}")
    (rev "A")
    (company "ProtoHUD")
  )
  (lib_symbols)
{body}
  (sheet_instances
    (path "/" (page "1"))
  )
)
""")

# ── Root sheet (hierarchical sheet objects) ─────────────────────────────────
sheet_objs = []
x, y = 25.4, 25.4
for i, (fname, title, _) in enumerate(SHEETS):
    sheet_objs.append(f"""  (sheet (at {x:.2f} {y:.2f}) (size 60 25) (fields_autoplaced)
    (stroke (width 0.1524) (type solid)) (fill (color 0 0 0 0.0000))
    (uuid {sheet_uuids[fname]})
    (property "Sheetname" "{title}" (at {x:.2f} {y-0.7:.2f} 0) {effects(1.27,'left bottom')})
    (property "Sheetfile" "{fname}.kicad_sch" (at {x:.2f} {y+25.8:.2f} 0) {effects(1.27,'left top')})
  )""")
    y += 32
    if (i + 1) % 4 == 0:
        y = 25.4
        x += 80

write(f"{PROJECT}.kicad_sch", f"""(kicad_sch
  (version {VERSION})
  (generator {GEN})
  (uuid {root_uuid})
  (paper "A3")
  (title_block
    (title "ProtoHUD Carrier Board — root")
    (rev "A")
    (company "ProtoHUD")
    (comment 1 "Hierarchical skeleton — see hardware/carrier-board docs")
  )
  (lib_symbols)
{chr(10).join(sheet_objs)}
  (sheet_instances
    (path "/" (page "1"))
  )
)
""")

# ── Project file (.kicad_pro) ───────────────────────────────────────────────
pages = '[\n      ["' + root_uuid + '", "Root"]'
for fname, title, _ in SHEETS:
    pages += ',\n      ["' + sheet_uuids[fname] + '", "' + title + '"]'
pages += "\n    ]"

write(f"{PROJECT}.kicad_pro", """{
  "board": { "design_settings": {}, "layer_presets": [], "viewports": [] },
  "boards": [],
  "cvpcb": { "equivalence_files": [] },
  "libraries": { "pinned_footprint_libs": [], "pinned_symbol_libs": [] },
  "meta": { "filename": "%s.kicad_pro", "version": 1 },
  "net_settings": { "classes": [ { "name": "Default", "clearance": 0.2 } ] },
  "pcbnew": { "page_layout_descr_file": "" },
  "schematic": {
    "drawing": {},
    "legacy_lib_dir": "",
    "legacy_lib_list": []
  },
  "sheets": %s,
  "text_variables": {}
}
""" % (PROJECT, pages))

print(f"Generated {PROJECT}.kicad_pro + root + {len(SHEETS)} sub-sheets in {HERE}")
